### ISSUE TITLE
Some of your vocabs are not ok; `skos:broader` VS `skos:topConceptOf`

### ISSUE THREAD

**Issue by sroertgen** [iqb-vocabs/Bildungstandard2023-erste-Fremdsprache-MSA#1]
During some maintenance and migration operations we noticed that some of your vocabularies are not valid.

E.g. https://github.com/iqb-vocabs/Bildungstandard2023-erste-Fremdsprache-MSA/blob/5808d98f9d7df46033bcadd642ec7ae107e120e8/iqb_erste%20Fremdsprache%20MSA_funktionalekommunikativekompetenz.ttl#L411

This Concept links with `skos:broader` to a concept scheme. But `skos:broader` is only used for linking `skos:Concept`s.
It should be `skos:topConceptOf` instead of `skos:broader`. Same applies for other top concepts.

The idea is: A concept scheme links to its topConcepts with `skos:hasTopConcept` and the concepts link back with `skos:topConceptOf`.

If you have any more questions, message me.

In order to get the vocabularies built properly I suggest to fix that.

**Comment by nanoyan** [comment]
Thank you Steffen for tip. We'll delete this Repository.
